Language: Python
cache:
- pip
python:
"3.5"
install:
- pip install coverage
- pip install coveralls
- pip install -r requirements.txt
script:
- nosetests
after_success:
- coverage report
- coveralls


